# Site
repository: alhmoreu/alhmoreu.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ana López-Hidalgo Moreu
title: Data Scientist | Industrial Engineer
email: ana.lmoreu@gmail.com
website: www.github.com/alhmoreu

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  alhmoreu
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: anlohidatascientist
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Ana and I started my journey into Data Science more than a year ago when I was convinced that the field of Data Science was the future of computer science and wanted to build my expertise on it.
  That is why I am very much interested in Applying Data Science techniques of Machine Learning and Artificial Intelligence to solve real world problems. As a Data Scientist I have experience in object-oriented programming, agile development methodology Scrum and algorithm analysis in the telecommunications sector. As an Industrial Engineer I have experience in research, planning and management in the energy sector. I have worked in different companies gaining strong analysis and problem solving skills, management and coordination of teams.

 “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
 ― Albert Einstein

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Telefónica
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Junior Data Scientist
        caption: November 2021 - Present
        # quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Autos Locos - Internal initiative to automate processes. Ongoing projects:
          - Mobile planning: Predict the behavior of STP traffic (2G and 3G networks) for
          each carrier
          - Classification and RCA of Low Throughput cells: Automation of cell sorting cells
          with low user download

          Technology Stack:
          Prophet - Statsmodels - Python - Pandas - Jira - GitLab - Splunk

      - layout: left
        title: Técnicas Reunidas
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Project Engineer in Heat Transfer Division
        caption: September 2019 - August 2020
        # quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          I worked in a multidisciplinary and multicultural team for the execution of refinery furnaces in
          Duqm Oman.
          Responsibilities:
          - Communication management with stakeholders
          - Expediting of engineering and suppliers
          - Control of scope and schedule
          - Technical tabulation of offers
          - Documentation control

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad Politécnica de Valencia
        caption: 2017 - 2019
        sub_title: Master in Industrial Engineering 
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          This 2 years programme Master's degree provides a solid scientific background, as well as a wide variety of knowledge in various industrial technologies (mechanical, electrical, electronic, automatic, materials, industrial buildings, projects, production, environment, energy and industrial organization) for free exercise of the profession.

          Registration of Honor in:
            - Business management
            - Instrumentation and Industrial Control
          
          Master thesis: Design of a Local Electricity Market model to favor the integration of distributed energy resources in competitive electrical systems: application to the island of Menorca

      - layout: left
        title: Universidad Politécnica de Madrid
        caption: 2012 - 2016
        sub_title: Degree of Energy Engineering 
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Member of the Energy Engineering Department Council as a student representative in the 2015/16 academic year.
          The goal of this Bachelor is to endow engineers with expertise in renewable and conventional energy, energy efficiency and efficient consumption.
          Specialisation: Energy Technologies (power generation, renewable energies, electricity markets, nuclear technology)

          Registration of Honor in:
            - Fundamentals of Power Electronics
            - Radiological Protection
            - Nuclear Security
            - Business Management

          Degree thesis: Tecnology and tests with a proton exchange membrane fuel cell

  - title: Online Certified courses
    layout: text
    content: | # this will include new lines to allow paragraphs
      Stanford online:
        - Machine Learning
      Deep Learning AI
        - Neural Networks and Deep Learning
        - Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization
        - Structuring Machine Learning Projects
        - Convolutional Neural Networks
        - Sequence Models
      Kaggel
        - Advanced SQL

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Machine Learning and Deep Learning some of my other interests and hobbies are:
      - Dance
      - Swimming
      - Reading


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
