# Site
repository: alhmoreu/alhmoreu.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ana López-Hidalgo Moreu
title: Data Scientist | Industrial Engineer
email: ana.lmoreu@gmail.com
website: www.github.com/alhmoreu

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  alhmoreu
linkedin_username: anlohidatascientist


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Ana and I started my journey into Data Science more than a year ago when I was convinced that this field would be the future of computer science and wanted to build my expertise on it.

  As a Data Scientist I have experience in object-oriented programming, agile development methodology Scrum and algorithm analysis in the telecommunications sector. 
  As an Industrial Engineer I have experience in research, planning and management in the energy sector. 

  “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
  ― Albert Einstein

content:
  - title: Skills
    layout: text
    content: |
      Programming 
       - Intermediate level of Python
       - Experience with Python using libraries like Numpy, Pandas, TensorFlow and Pytorch
       - Experience with object-oriented programming

      
      Software Development
       - Experience with the Scrum agile development methodology
       - Experience with Linux, bash and Git/Github for version control
       - Automation of processes with daemons (Cron)

      Machine learning
       - Knowledge of the mathematical foundations of Machine Learning
       - Experience with supervised and unsupervised learning algorithms
       - Experience with Deep Learning and the use of different types of neural networks

      Database
       - Intermediate level of SQL

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Telefónica
        sub_title: Junior Data Scientist
        caption: November 2021 - Present
        description: | 
          Autos Locos - Internal initiative to automate processes. Ongoing projects:
          - Mobile planning: Predict the behavior of STP traffic (2G and 3G networks) for
          each carrier
          - Classification and RCA of Low Throughput cells: Automation of cell sorting cells
          with low user download

          Technology Stack:
          Prophet - Statsmodels - LightGBM - <mark>Python</mark> - <mark>Pandas</mark> - Jira - <mark>GitLab</mark> - Splunk

      - layout: left
        title: Técnicas Reunidas
        sub_title: Project Engineer in Heat Transfer Division
        caption: September 2019 - August 2020
        description: | 
          I worked in a multidisciplinary and multicultural team for the execution of refinery furnaces in
          Duqm Oman.
          Responsibilities:
          - Communication management with stakeholders
          - Expediting of engineering and suppliers
          - Control of scope and schedule
          - Technical tabulation of offers
          - Documentation control

  - title: Education 
    layout: list 
    content:
      - layout: left
        title: Universidad Politécnica de Valencia
        caption: 2017 - 2019
        sub_title: Master in Industrial Engineering 
        description: | 
          This 2 years programme Master's degree provides a solid scientific background, as well as a wide variety of knowledge in various industrial technologies (mechanical, electrical, electronic, automatic, materials, industrial buildings, projects, production, environment, energy and industrial organization) for free exercise of the profession.
          
          _Master thesis_: Design of a Local Electricity Market model to favor the integration of distributed energy resources in competitive electrical systems: application to the island of Menorca
          
          **Registration of Honor in**:
            - Business management
            - Instrumentation and Industrial Control

      - layout: left
        title: Universidad Politécnica de Madrid
        caption: 2012 - 2016
        sub_title: Degree of Energy Engineering 
        description: | 
          _Activities_: Member of the Energy Engineering Department Council as a student representative in 2015-16.
          
          This Bachelor endows engineers with expertise in renewable and conventional energy, energy efficiency and efficient consumption.

          _Degree thesis_: Tecnology and tests with a proton exchange membrane fuel cell

          **Registration of Honor in**:
            - Fundamentals of Power Electronics
            - Radiological Protection
            - Nuclear Security
            - Business Management


  - title: Online Certified courses 
    layout: list 
    content:
      - layout: left
        title: Stanford Online University
        caption: 2020 - 2021
        sub_title:  Machine Learning Course
        description: | 
          This course takes about 11 weeks to complete. It teaches how to extract and identify useful features that best represent your data, some of the most important machine learning algorithms, and how to evaluate the performance of algorithms.

      - layout: left
        title: DeepLearning.AI
        caption: 2020 - 2021
        sub_title: Deep Learning Specialization
        description: | 
          There are 5 courses in this Deep Learning Specialization Course. In this Specialization, you built neural network architectures such as Convolutional Neural Networks, Recurrent Neural Networks, LSTMs, Transformers, and learned how to make them better with strategies such as Dropout, BatchNorm, and Xavier/He initialization. You mastered these theoretical concepts, learned their industry applications using Python and <mark>TensorFlow</mark>, and tackled real-world cases such as autonomous driving, speech recognition, music synthesis, chatbots, machine translation, natural language processing, and more. You are now familiar with the capabilities and challenges of deep learning.
          - Neural Networks and Deep Learning
          - Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization
          - Structuring Machine Learning Projects
          - Convolutional Neural Networks
          - Sequence Models


  - title: A Little More About Me
    layout: text
    content: | 
      Alongside my interests in Machine Learning and Deep Learning some of my other interests and hobbies are:
      - Dance     - Swimming     - Play padel
      - Reading   - Solve brainteasers   - Financial Markets
      - Environment
              


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
