# Site
repository: alhmoreu/alhmoreu.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ana López-Hidalgo Moreu
title: Data Scientist | Industrial Engineer
email: ana.lmoreu@gmail.com
website: www.github.com/alhmoreu

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  alhmoreu
linkedin_username: anlohidatascientist


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Ana and I started my journey into Data Science more than three years ago when I was convinced that this field would be the future of computer science and wanted to build my expertise on it.

  As a Data Scientist I have experience in machine learning, particularly in anomaly detection and time series forecasting. I've been involved in every aspect of projects, from digging into data and analyzing it to deploying models in production.

  As an Industrial Engineer I have experience in research, planning and management in the energy sector. 

  ― “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
  ― Albert Einstein

content:
  - title: Skills
    layout: text
    content: |
      Programming
       - Intermediate level in Python with experience using libraries such as Numpy, Pandas and Scikit-learn.
       - Experience with object-oriented programming (OOP).

      Machine Learning
       - Solid understanding of the mathematical foundations of Machine Learning.
       - Experience with supervised and unsupervised learning algorithms.

      Data Visualization
       - Experience using Python libraries such as Matplotlib, Seaborn and Plotly.
       - Experience with Power BI for business intelligence.

      Software Development
       - Experience working with the Scrum agile development methodology.
       - Familiarity with Linux, bash and Git/Github for version control.
       - Automation of processes with daemons (Cron).

      Data Technologies
       - Intermediate level of SQL.
       - Intermediate level of PySpark.
       
      Cloud
       - Experience with Amazon Web Services.
       - Experience with Microsoft Azure.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Inditex
        sub_title: Data Scientist
        caption: September 2022 - Present
        description: | 
          I have been involved in the following projects:
          - Anomaly detection in ambient temperature signals and energy consumption within stores.
          - Monthly energy consumption forecasting for Inditex stores.
          - Anomaly detection in people-counting devices installed in stores.
          - Estimation of the number of people entering and exiting retail stores.

          Technology Stack:
          Clustering Models - Statistical Models - XGBoost - <mark>Pyspark</mark> - <mark>GitHub</mark> - <mark>Microsoft Azure</mark>

      - layout: left
        title: Telefónica
        sub_title: Junior Data Scientist
        caption: November 2021 - September 2022
        description: | 
          Autos Locos - Internal initiative to automate processes. Ongoing projects:
          - Mobile planning: Predict the behavior of STP traffic (2G and 3G networks) for
          each carrier.
          - Classification and RCA of Low Throughput cells: Automation of cell sorting cells
          with low user download.

          Technology Stack:
          Prophet - Statsmodels - LightGBM - <mark>Python</mark> - <mark>Pandas</mark> - Jira - <mark>GitLab</mark> - Splunk - <mark>AWS</mark>

      - layout: left
        title: Técnicas Reunidas
        sub_title: Project Engineer in Heat Transfer Division
        caption: September 2019 - August 2020
        description: | 
          I worked in a multidisciplinary and multicultural team for the execution of refinery furnaces in
          Duqm Oman.
          Responsibilities:
          - Communication management with stakeholders.
          - Expediting of engineering and suppliers.
          - Control of scope and schedule.
          - Technical tabulation of offers.
          - Documentation control.

  - title: Education 
    layout: list 
    content:
      - layout: left
        title: Universidad Politécnica de Valencia
        caption: 2017 - 2019
        sub_title: Master in Industrial Engineering 
        description: | 
          This 2 years Master's degree expands knowledge in industrial technologies, including mechanical, electrical, electronic, automation, materials science, industrial buildings, project management, production, energy, and industrial organization, to enable professional practice in these fields.
          
          _Master thesis_: Design of a Local Electricity Market model to favor the integration of distributed energy resources in competitive electrical systems: application to the island of Menorca.
          
          **Registration of Honor in**:
            - Business management.
            - Instrumentation and Industrial Control.

      - layout: left
        title: Universidad Politécnica de Madrid
        caption: 2012 - 2016
        sub_title: Degree of Energy Engineering 
        description: |   
          This Bachelor endows engineers with expertise in renewable and conventional energy, energy efficiency and efficient consumption.

          _Degree thesis_: Tecnology and tests with a proton exchange membrane fuel cell.

          _Activities_: Member of the Energy Engineering Department Council as a student representative in 2015-16.

          **Registration of Honor in**:
            - Fundamentals of Power Electronics.
            - Radiological Protection.
            - Nuclear Security.
            - Business Management.


  - title: Online Certified courses 
    layout: list 
    content:
      - layout: left
        title: Stanford Online University
        caption: 2020 - 2021
        sub_title:  Machine Learning Course
        description: | 
          This course covers the application of advanced machine learning algorithms to problems such as anti-spam, image recognition, clustering, and recommender systems. It also includes training on selecting the appropriate algorithms and improving their performance through debugging and optimization.

      - layout: left
        title: DeepLearning.AI
        caption: 2020 - 2021
        sub_title: Deep Learning Specialization
        description: | 
          This Deep Learning Specialization consists of 5 courses that cover building neural network architectures like Convolutional Neural Networks, Recurrent Neural Networks, LSTMs, and Transformers. It includes techniques to improve these networks, such as Dropout and BatchNorm, and applications using Python and TensorFlow. The specialization addresses real-world cases including autonomous driving, speech recognition, and natural language processing, providing a comprehensive understanding of deep learning capabilities and challenges.
          - Neural Networks and Deep Learning
          - Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization
          - Structuring Machine Learning Projects
          - Convolutional Neural Networks
          - Sequence Models


  - title: A Little More About Me
    layout: text
    content: | 
      Outside of work, dance is a significant part of my life. I’ve danced ballet for over ten years and enjoy contemporary dance and salsa. I also love reading and learning languages, like Chinese. Swimming is my personal escape, and I enjoy spending time with friends and connecting with nature.
              


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
